### ISSUE TITLE
Video is not loading

### ISSUE THREAD

**Issue by shubhamrb** [salvadordeveloper/TikTok-Flutter#12]
E/flutter (17787): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0
E/flutter (17787): #0      List.[] (dart:core-patch/growable_array.dart:177:60)
E/flutter (17787): #1      FeedViewModel.loadVideo (package:tiktok_flutter/screens/feed_viewmodel.dart:35:33)
E/flutter (17787): #2      _FeedScreenState.initState (package:tiktok_flutter/screens/feed_screen.dart:28:19)
E/flutter (17787): #3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4765:58)
E/flutter (17787): #4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (17787): #5      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (17787): #6      Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (17787): #7      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (17787): #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (17787): #9      Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (17787): #10     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (17787): #11     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (17787): #12     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (17787): #13     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (17787): #14     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (17787): #15     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (17787): #16     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (17787): #17     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (17787): #18     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (17787): #19     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (17787): #20     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (17787): #21     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (17787): #22     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (17787): #23     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter (17787): #24     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (17787): #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (17787): #26     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
E/flutter (17787): #27     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (17787): #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (17787): #29     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (17787): #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (17787): #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (17787): #32     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (17787): #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6118:14)
E/flutter (17787): #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (17787): #35     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (17787): #36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (17787): #37     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter (17787): #38     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (17787): #39     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4606:5)
E/flutter (17787): #40     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4791:11)
E/flutter (17787): #41     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4601:5)
E/flutter (17787): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
E/flutter (17787): #43     Element.updateChild (package:flutter/src/widgets/framework.dart:3327:18)
E/flutter (17787): #44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
E/flutter (17787): #45     Element.rebuild (package:flutter/src/widgets/framework.dart:

**Comment by stiltet** [comment]
I had the same issue and managed to fix it by updating the following in _"feed_viewmodel.dart"_:

ORIGINAL CODE:

`  changeVideo(index) async {
    videoSource.listVideos[prevVideo].controller.pause();
    if (videoSource.listVideos[index].controller == null) {
      await videoSource.listVideos[index].loadController();
    }
    videoSource.listVideos[index].controller.play();
    videoSource.listVideos[prevVideo].controller.removeListener(() {});

    //videoSource.listVideos[prevVideo].controller.dispose();

    prevVideo = index;
    notifyListeners();

    print(index);
  }`

FIXED CODE:

`  changeVideo(index) async {
    if (videoSource.listVideos[prevVideo].controller != null) {
      videoSource.listVideos[prevVideo].controller.pause();
      videoSource.listVideos[prevVideo].controller.removeListener(() {});
    }
    if (videoSource.listVideos[index].controller == null) {
      await videoSource.listVideos[index].loadController();
    }
    videoSource.listVideos[index].controller.play();

    //videoSource.listVideos[prevVideo].controller.dispose();

    prevVideo = index;
    notifyListeners();

    print(index);
  }`

**Comment by JITENDRA7104** [comment]
hi,
not loading video. please resolved my this issues

**Comment by danielgchap** [comment]
Please help.... I'm getting the following...

[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/growable_array.dart:254:60)
#1      FeedViewModel.loadVideo (package:instapray/screens/video_wall/feed_viewmodel.dart:37:33)
#2      _FeedScreenState.initState (package:instapray/screens/video_wall/feed_screen.dart:29:19)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4632:57)

All I did was download clone and fire up against a firebase proj. Everything else is 100% on point. But the model tries to get the videos before list is loaded, even though the list loads.
