### ISSUE TITLE
Getting Error

### ISSUE THREAD

**Issue by RaviKumarK25** [salvadordeveloper/TikTok-Flutter#3]
Hi @salvadordeveloper bro, please help me to solve this issue. I am getting error in these below codes

var userData = await Firestore.instance.collection("Users").where("username",isEqualTo: userId).getDocuments();
    var videosViewed = userData.documents[0].data['videosViewed'];

are you using any user table? please help me to solve my issue. I am waiting for your reply,

**Comment by salvadordeveloper** [comment]
Fixed, new sample data is added automatically to Firestore, if you want edit or add more data edit the file "demo_data.dart", is very easy to add or remove videos, is in format json.
