### ISSUE TITLE
Can you make a tutorial for this please?

### ISSUE THREAD

**Issue by akshaybalaji123** [salvadordeveloper/TikTok-Flutter#6]
@salvadordeveloper  Hello, I am really liking this whole idea. Could you perhaps make a youtube tutorial on this. Also I want to know where do I add the google-services.json and what rules do I need to change in the firebase?

**Comment by salvadordeveloper** [comment]
Hi, sorry at this moment I can't make a tutorial for this. Is a project very large and I first need to implement a lot of things. But I going to do a guide more explained on how to configure the project.

**Comment by akshaybalaji123** [comment]
In the guide can you tell us step by step which files to add first etc so that I could replicate this myself? Also what do I need to configure in the Firebase side of it?

**Comment by akshaybalaji123** [comment]
Where do I put google services.json
