### ISSUE TITLE
Google credentials in public repo?

### ISSUE THREAD

**Issue by cesumilo** [salvadordeveloper/TikTok-Flutter#7]
Hi,

Just to tell you that your [google credentials are available](https://github.com/salvadordeveloper/TikTok-Flutter/blob/master/GoogleService-Info.plist) within the repository. Hope your credit card is not liked to it 😉 

Regards,

Guillaume

**Comment by salvadordeveloper** [comment]
Hi, thanks for your notice! Fortunately, I not have credit card in my account, but anyway I going to remove the file with my info from the repo.
