### ISSUE TITLE
Icon getter not defined

### ISSUE THREAD

**Issue by TheFutureStartsNow** [salvadordeveloper/TikTok-Flutter#9]
I running it in Android Studio and i am getting this messages as well:

error: The getter 'person_add_alt_1_outlined' isn't defined for the type 'Icons'. (undefined_getter at [tiktok_flutter] lib/screens/profile_screen.dart:21)

error: The getter 'qr_code' isn't defined for the type 'Icons'. (undefined_getter at [tiktok_flutter] lib/screens/search_screen.dart:43)

Any idea how to resolve this?

**Comment by glaksmono** [comment]
I'm also getting this issue

**Comment by enviro-apps** [comment]
Just select a different icon they are maybe deprecated you can also try to downgrade flutter

**Comment by Lekhansh-dev** [comment]
I'm also getting this issue

**Comment by Lekhansh-dev** [comment]
> I'm also getting this issue 

Just replace this word and type search

**Comment by MUKESHYADAV203** [comment]
I am getting same issues
